{
 "title": "Servicio de inferencia",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "NVIDIA Triton Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alive",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "Triton activo" }
   ]
  },
  {
   "title": "nv_energy_consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nv_energy_consumption[5m])",
     "legendFormat": "nv_energy_consumption"
    }
   ]
  },
  {
   "title": "nv_gpu_utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "nv_gpu_utilization" }
   ]
  },
  {
   "title": "nv_inference_count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nv_inference_count", "legendFormat": "Inferencias" }
   ]
  },
  {
   "title": "Input",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_compute_input_duration_us",
     "legendFormat": "nv_inference_compute_input_duration_us"
    }
   ]
  },
  {
   "title": "Inference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_duration_us",
     "legendFormat": "nv_inference_compute_infer_duration_us"
    }
   ]
  },
  {
   "title": "Output",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nv_inference_compute_output_duration_us",
     "legendFormat": "nv_inference_compute_output_duration_us"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nv_gpu_memory_used_bytes", "legendFormat": "nv_gpu_memory_used_bytes" },
    { "expr": "nv_gpu_memory_total_bytes", "legendFormat": "nv_gpu_memory_total_bytes" }
   ]
  }
 ]
}